import { MD3LightTheme, MD3DarkTheme } from "react-native-paper";

export const lightTheme = {
  ...MD3LightTheme,
  colors: {
    ...MD3LightTheme.colors,
    background: "#ffffff",
    surface: "#ffffff",
    onBackground: "#18181b",
    onSurface: "#18181b",
    primary: "#18181b",
    onPrimary: "#fafafa",
    primaryContainer: "#f4f4f5",
    onPrimaryContainer: "#18181b",
    secondary: "#71717a",
    secondaryContainer: "#f4f4f5",
    onSecondary: "#ffffff",
    onSecondaryContainer: "#18181b",
    tertiary: "#71717a",
    tertiaryContainer: "#f4f4f5",
    onTertiary: "#ffffff",
    onTertiaryContainer: "#18181b",
    surfaceVariant: "#f4f4f5",
    onSurfaceVariant: "#71717a",
    outline: "#e4e4e7",
    outlineVariant: "#e4e4e7",
    error: "#ef4444",
    onError: "#ffffff",
    errorContainer: "#fef2f2",
    onErrorContainer: "#b91c1c",
    elevation: {
      ...MD3LightTheme.colors.elevation,
      level0: "transparent",
      level1: "#ffffff",
      level2: "#f4f4f5",
      level3: "#f4f4f5",
      level4: "#f4f4f5",
      level5: "#f4f4f5",
    },
  },
};

export const darkTheme = {
  ...MD3DarkTheme,
  colors: {
    ...MD3DarkTheme.colors,
    background: "#09090b",
    surface: "#09090b",
    onBackground: "#fafafa",
    onSurface: "#fafafa",
    primary: "#fafafa",
    onPrimary: "#18181b",
    primaryContainer: "#27272a",
    onPrimaryContainer: "#fafafa",
    secondary: "#a1a1aa",
    secondaryContainer: "#27272a",
    onSecondary: "#18181b",
    onSecondaryContainer: "#fafafa",
    tertiary: "#a1a1aa",
    tertiaryContainer: "#27272a",
    onTertiary: "#18181b",
    onTertiaryContainer: "#fafafa",
    surfaceVariant: "#27272a",
    onSurfaceVariant: "#a1a1aa",
    outline: "#27272a",
    outlineVariant: "#27272a",
    error: "#ef4444",
    onError: "#ffffff",
    errorContainer: "#450a0a",
    onErrorContainer: "#fca5a5",
    elevation: {
      ...MD3DarkTheme.colors.elevation,
      level0: "transparent",
      level1: "#09090b",
      level2: "#18181b",
      level3: "#18181b",
      level4: "#18181b",
      level5: "#18181b",
    },
  },
};
